### ISSUE TITLE
can't find where "aoe2de_patcher.exe" is for the life of me

### ISSUE THREAD

**Issue by Sawyer7105** [DJSchaffner/aoe2de_patcher#12]
Sorry to bother you in this way, I just cannot find where the "aoe2de_patcher.exe" file is for the life of me. 

I start by going to your aoe2de_patcher github page. I click on the green "<>code" button and click download zip. Then i open the "aoe2de_patcher-master zip folder and cannot see where the .exe file is? Please help me. Thanks, and Ill buy you a coffee later!

**Comment by DJSchaffner** [comment]
Did you find it? :D
Here's a link to current latest version: https://github.com/DJSchaffner/aoe2de_patcher/releases/tag/v2.10
Download the 13.1mb file there. The way you described, you downloaded the sourcecode. I get github is not providing the best UI for someone who is not used to it.
