### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sawyer7105** [DJSchaffner/aoe2de_patcher#13]
**Describe the bug**
When I try to launch the "aoe2de_patcher" application it comes up with an error that it cannot find "python310.dll" file. As you can see in the screenshot, the python file is right there on the screen below the popup. I'm stumped as to why this is an issue. I have Norton security on my computer and thought that could have blocked certain files so I turned that security stuff completely off disabling everything and still got the same issue. If you could help me, I would really appreciate it. Thank you!

**To Reproduce**
1. downloaded your latest version of "aoe2de_patcher". 
2. opened the zip file "aoe2de_patcher" 
3. opened the "aoe2de_patcher folder"
4. scrolled down the page and double clicked on "aoe2de_patcher" application.
5. pop-up on screen appears and says "This application may depend on other compressed files in this folder. For the application to run properly, it is recommended that you first extract all files"
6. I clicked extract all
7. new pop-up with file destination, I click "Extract"
8. I open "aoe2de_patcher" folder
9. I scroll down and double click "aoe2de_patcher" application.
10. Windows Defender firewall pops up and asks me if I'm sure I want to run the program, I click "more info" and the click "run anyway"
11. Error appears that says "aoe2de_patcher.exe - System Error" "The code execution cannot proceed because python310.dll was not found. Reinstalling the program may fix the problem." 

**Expected behavior**
I expected the patcher to run on its own, not sure why it cannot find the python file when in the screenshot you can see it in the folder list right below.

**Screenshots**
![IMG_4079](https://github.com/DJSchaffner/aoe2de_patcher/assets/169721524/ee8aaddd-10ef-4a41-80c4-3527ce3b7a18)

Thanks so much for your help!! :)

**Comment by DJSchaffner** [comment]
Hey there, and thank you for your report :)

I feel like someone else had a similar problem before, and he did not unzip the archive but tried to launch it inside the zip file. Can you confirm that you have indeed extracted the zip file to a folder on your disk and launched it from there?

**Comment by Sawyer7105** [comment]
I downloaded "WinZip" and it unzipped it correctly and the patcher opened!!
Thank you for explaining that. One last question, what do I pick as the
game directory?

**Comment by DJSchaffner** [comment]
Good to hear!
You have to select the folder that contains the AoE2DE excecutable file. For me it is this for example: `C:\Program Files (x86)\Steam\steamapps\common\AoE2DE` it might be the same for you, depending on where you installed it

**Comment by Sawyer7105** [comment]
Everything is now patched successfully. I got the pop that said “Done”.
When I try to run aoe2de from either steam or a desktop shortcut it runs
for 10 seconds, then stops. I click to play again on steam, it says running
in blue, then goes back to a green play button again after 10 seconds.
Any ideas?

**Comment by DJSchaffner** [comment]
Yeah I have seen that one. Unfortunately I didn't find a way around that one so far. You can try a few things like running the game as administrator (launch from the aoe2 exe manually, not via steam), try compatibility mode for windows 10/8/7 but if none of those work, I fear there is no real solution apart from trying again.

I hoped that one would have been fixed since I didn't encounter it the last few times I patched, but seems it is still around 😢 
It has been forwarded to the devs of aoe, since there is probably nothing to be done from this side but no news on it so far.

On the positive side: Once you got it to launch once, it usually just keeps working after that.

**Comment by Sawyer7105** [comment]
Hey DJSchaffner,

I tried all the options that you suggested and nothing has worked. I
decided I wanted to go another route and *I wanted to ask you if you were
interested in a "work opportunity" for commission. You seem very skilled
and knowledgeable about this kind of stuff.* Basically, I haven't been able
to contact the mod creators since this mod is 3 years old and deleted from
modDB a while back. Basically, it seems that the issue is that the Json
files think there are 39 civs but now after game updates there are 45 civs.
So in theory, if the mods are updated it should work, I just have little to
no knowledge as to how to update them. I have tried using an advanced genie
editor with help from vague reddit forums, but that didn't work. There are
4 mods that all need to be updated, they all work together in game to
completely overhaul aoe2 into LOTR Tales of Middle Earth.

My proposition is to pay you commission to update these mods into working
order with the current build of aoe2 DE. Last time I used them was july
2021 and for 3 months all 4 mods worked seamlessly together, so I know they
can run on that current build. With your aoe2 patcher I was hoping to just
revert the version of aoe2 DE back to july 2021 and play it that way, but
with my game crashing and not able to run the game after patching I figured
I could have you update the mods yourself.

So... here's my idea:

*For $250:*
*-you get all 4 Lord of the Rings overhaul mods to keep (1 data mod, 1
graphics mod, 1 language mod, and 1 voicework/ ui mod)*
*-you test them on your aoe2 patcher on july 2021 patch to see if they work
for you on your end first without updating mods. (just curious if they
would work on patcher if my computer wouldn't crash)*
*-you update all 4 mods to work on the current 2024 build of aoe2 DE*
*-complete this project within a reasonable time table (roughly within 2-3
weeks prefered) My estimation of how long it should take you to update the
mods physically is a few hours so good $/hour rate.*

optional:
-you show me after how to update the mods to keep them relevant and working
in the future.

*I am flexible on pricing, timeframe, and would be eternally grateful for
your help. If you cannot help me, if you have others that you could refer
me to that would be much appreciated.

Notes:
-Below is an image of the error message that appears when I try to run the
mods on the current 2024 build.
-If you go online and search Tales of middle earth aoe2 you can see the old
HD screenshots of how the graphics, units, etc are changed so that
everything looks like LOTR. (for context of what the mods will do in DE)

Hopefully you can help me, thanks for your time!

Sincerely,
Thomas

**Comment by DJSchaffner** [comment]
Hey Thomas,

I am currently out of town for work until Friday evening. I will read through your message and get back to you when I am back home!

Cheers :)
________________________________

**Comment by DJSchaffner** [comment]
Alright, I am back and took a quick look at what you need. First of all: I haven't done any modding in AoE 2, so no promises, but the problem sounds easy enough so that I could probably get it done without much knowledge.

Can you provide me with the mod files? From what I found after a quick search, they are no longer hosted online because of a copyright claim.

Also, you could contact me on discord if you want since this is probably not the best channel of communication for this. You can find me as `djschaffner`

Cheers :)

**Comment by Sawyer7105** [comment]
Hey djschaffner,

This is great news. I sent you a friend request on discord as "hero55343".
I never use discord and wasn't sure if this is needed to start
conversation/DMs.

Thanks again for your help.
