### ISSUE TITLE
[BUG] installed version does not support downgrading

### ISSUE THREAD

**Issue by Bart-van-der-Lugt** [DJSchaffner/aoe2de_patcher#14]
**Describe the bug**
After downloading the latest version of the patcher (2.11) and following the steps described in the readme, an error is thrown saying the currently installed version does not support downgrading.

**To Reproduce**
1. Go to the most recent patcher
2. Fill in credentials and steam app folder
3. Click on patch 
5. See error

**Expected behavior**
No error

**Screenshots**
![afbeelding](https://github.com/user-attachments/assets/4b5f2096-da73-4c57-912d-d64ca4934e42)

**Comment by DJSchaffner** [comment]
Thanks for your report :)
Should be fixed in a couple of minutes

**Comment by Bart-van-der-Lugt** [comment]
No problem, thank you for responding so fast. Should I keep an eye out for a new release?

**Comment by DJSchaffner** [comment]
No need to download a new version. The tool pulls the info from the github repo. If you need to update it will tell you on startup
