### ISSUE TITLE
The installed version currently doesn't support downgrading.

### ISSUE THREAD

**Issue by kmanan** [DJSchaffner/aoe2de_patcher#3]
The installed version currently doesn't support downgrading. Please be patient or notify me on GitHub!
Error during download!
Could not patch!

Going from 66692 to 63581 is not possible

**Comment by DJSchaffner** [comment]
Thanks for notifying me!
I will take a look at it

**Comment by DJSchaffner** [comment]
Looks like the versioning changed for aoe. I'll have to find a new way of checking the installed game version and probably have to release a new version of the tool for it.

Keep an eye out for a new version tonight or tomorrow.

**Comment by kmanan** [comment]
🙏🏽🙏🏽🙏🏽

**Comment by kmanan** [comment]
It works flawlessly!! Will let you know if I see any issue. Thanks!
