### ISSUE TITLE
Tried running the new tool, downloads 0 data from Steam, says it is patched but replay doesn't run

### ISSUE THREAD

**Issue by kmanan** [DJSchaffner/aoe2de_patcher#4]
Not sure what I am doing wrong but the patcher doesn't seem to download anything from Steam, and when i run the old replay, it doesn't work. Here's what the patcher says:

```
Game directory set to: C:\Program Files (x86)\Steam\steamapps\common\AoE2DE
Installed version detected: 66692
Starting download phase
Generating list of changes
Connecting to Steam3... Done!

Logging 'fatalskeptic' into Steam3... Done!

Using Steam3 suggested CellID: 31

Got 15 licenses for account!

Got session token!

Got AppInfo for **<not sure if number is sensitive>**

Using app branch: 'Public'.

Got depot key for **<not sure if number is sensitive>** result: OK

Processing depot **<not sure if number is sensitive>** - Phoenix Content

Downloading depot manifest...Got manifest request code for **<not sure if number is sensitive>** 5760045920272352358 result: 4572355103252596208

 Done!

Manifest 5760045920272352358 (8/23/2022 4:48:53 AM)

Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots

Accepted new login key for account fatalskeptic

Disconnected from Steam

Connecting to Steam3... Done!

Logging 'fatalskeptic' into Steam3... Done!

Using Steam3 suggested CellID: 31

Got 15 licenses for account!

Got session token!

Got AppInfo for **<not sure if number is sensitive>**

Using app branch: 'Public'.

Got depot key for **<not sure if number is sensitive>** result: OK

Processing depot **<not sure if number is sensitive>** - Phoenix Content

Downloading depot manifest...Got manifest request code for **<not sure if number is sensitive>** 2164364554796430252 result: 13435627329229704174

 Done!

Manifest 2164364554796430252 (6/29/2022 2:01:54 AM)

Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots

Disconnected from Steam
```

**Comment by DJSchaffner** [comment]
Hey, sorry it doesn't seem to work for you.
I just tried running it for me again and it seems to work fine. Let's find out what's wrong here :D

Is that really the full log? It shouldn't stop there. I think in the next update I should add a log file for stuff like this.

**Comment by kmanan** [comment]
Yep that's the full log and everything is grayed out in the UI after this. 
![image](https://user-images.githubusercontent.com/17659155/188291480-77b02763-156f-4092-bb0b-f14bc0bd9734.png)

**Comment by DJSchaffner** [comment]
The UI being greyed out and missing the usual steps for being done means it's not really done yet.   

Are you sure there is nothing happening after that? Did you give it a moment, or did it get stuck there?
The third step in the last patch is quite big, so it might take a moment to start.

**Comment by kmanan** [comment]
hah! Impatience is definitely an issue. Unfortunately, duration hasn't mattered. I've left it like this for 40+ mins with no new "update" to this log, no network activity, it says Total downloaded: 0 bytes so doesn't seem like it is has been downloading anything.

**Comment by DJSchaffner** [comment]
Interesting. If you want you can try this test version of the tool. It will log the output text to a file when you close it and also log the error messages so if there is something happening in the background we should be able to see it. You can just upload the logfile or a screenshot afterwards.

BTW: the executable is called main.exe here
[main.dist.zip](https://github.com/DJSchaffner/aoe2de_patcher/files/9485168/main.dist.zip)

**Comment by kmanan** [comment]
Game directory set to: C:\Program Files (x86)\Steam\steamapps\common\AoE2DE
Installed version detected: 66692
Starting download phase
Generating list of changes
Connecting to Steam3... Done!

Logging 'fatalskeptic' into Steam3...Disconnected from Steam

This account is protected by Steam Guard.

Please enter the authentication code sent to your email address: Retrying Steam3 connection... Done!

Logging 'fatalskeptic' into Steam3... Done!

Using Steam3 suggested CellID: 31

Got 15 licenses for account!

Got session token!

Got Machine Auth: ssfn5764044581961791249 0 2048 2048

Accepted new login key for account fatalskeptic

Got AppInfo for 813780

Using app branch: 'Public'.

Got depot key for 813781 result: OK

Processing depot 813781 - Phoenix Content

Downloading depot manifest...Got manifest request code for 813781 5760045920272352358 result: 6966791837866639001

 Done!

Manifest 5760045920272352358 (8/23/2022 4:48:53 AM)

Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots

Disconnected from Steam

Connecting to Steam3... Done!

Logging 'fatalskeptic' into Steam3... Done!

Using Steam3 suggested CellID: 31

Got 15 licenses for account!

Got session token!

Got AppInfo for 813780

Using app branch: 'Public'.

Got depot key for 813781 result: OK

Processing depot 813781 - Phoenix Content

Downloading depot manifest...Got manifest request code for 813781 2164364554796430252 result: 15167239488096001374

 Done!

Manifest 2164364554796430252 (6/29/2022 2:01:54 AM)

Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots

Disconnected from Steam

Exception in thread Thread-1 (work):
Traceback (most recent call last):
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\threading.py", line 946, in run
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\main.py", line 127, in work
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 75, in patch
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 234, in _download_patch
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 456, in _get_filelist
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 514, in _read_manifest
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\_strptime.py", line 562, in _strptime_time
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\_strptime.py", line 349, in _strptime
ValueError: time data '8/23/2022 4:48:53 AM' does not match format '%d.%m.%Y %H:%M:%S'

**Comment by kmanan** [comment]
So maybe here's what's happening, my PC time is m/d/y but my Steam account is set to india which is d/m/y, and that's probably breaking the code for the patcher?

**Comment by kmanan** [comment]
Didn't seem to work, I changed the Windows system date setting and didn't work:

 Game directory set to: C:\Program Files (x86)\Steam\steamapps\common\AoE2DE
Installed version detected: 66692
Starting download phase
Generating list of changes
Connecting to Steam3... Done!

Logging 'fatalskeptic' into Steam3... Done!

Using Steam3 suggested CellID: 31

Got 15 licenses for account!

Got session token!

Got AppInfo for 813780

Using app branch: 'Public'.

Got depot key for 813781 result: OK

Processing depot 813781 - Phoenix Content

Downloading depot manifest...Got manifest request code for 813781 5760045920272352358 result: 7221801826874748899

 Done!

Manifest 5760045920272352358 (23-08-2022 04:48:53)

Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots

Accepted new login key for account fatalskeptic

Disconnected from Steam

Connecting to Steam3... Done!

Logging 'fatalskeptic' into Steam3... Done!

Using Steam3 suggested CellID: 31

Got 15 licenses for account!

Got session token!

Got AppInfo for 813780

Using app branch: 'Public'.

Got depot key for 813781 result: OK

Processing depot 813781 - Phoenix Content

Downloading depot manifest...Got manifest request code for 813781 2164364554796430252 result: 6406142112245968561

 Done!

Manifest 2164364554796430252 (29-06-2022 02:01:54)

Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots

Disconnected from Steam

Exception in thread Thread-1 (work):
Traceback (most recent call last):
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\threading.py", line 946, in run
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\main.py", line 127, in work
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 75, in patch
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 234, in _download_patch
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 456, in _get_filelist
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\logic.py", line 514, in _read_manifest
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\_strptime.py", line 562, in _strptime_time
  File "C:\Users\manan\DOWNLO~1\AOE2PA~1\MAIN~1.DIS\_strptime.py", line 349, in _strptime
ValueError: time data '23-08-2022 04:48:53' does not match format '%d.%m.%Y %H:%M:%S'

**Comment by DJSchaffner** [comment]
That is indeed strange :D
I'm trying to find out what's going on and report back when I find something or need more info.

Maybe one more thing: Did the tool work for you in previous patches?

**Comment by DJSchaffner** [comment]
I just posted a new release which should fix this issue. For now, I just stopped parsing the date as it is never used anyways.

Let me know if it's really fixed for you, and thank you for reporting and helping with finding the problem :)

**Comment by kmanan** [comment]
THE NEW RELEASE WORKED!!
