### ISSUE TITLE
Directory not being read?

### ISSUE THREAD

**Issue by SolomonRed** [DJSchaffner/aoe2de_patcher#6]
I appear to be have an issue with the directory not being read or an issue where the .net program was isntalled?

The directory mentioned in the error message does not match the one I chose for the game files. I appreciate any help resolving this, looking to restore the game to the state prior to the April patch.

**Full log below:**

Please select a game directory
Game directory set to: C:\Program Files (x86)\Steam\steamapps\common\AoE2DE
Installed version detected: 81058
Starting download phase
Generating list of changes
Could not execute because the specified command or file was not found.

Possible reasons for this include:

  * You misspelled a built-in dotnet command.

  * You intended to execute a .NET program, but dotnet-C:\Users\Ports\Downloads\Aoe does not exist.

  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Error logging into account
Could not execute because the specified command or file was not found.

Possible reasons for this include:

  * You misspelled a built-in dotnet command.

  * You intended to execute a .NET program, but dotnet-C:\Users\Ports\Downloads\Aoe does not exist.

  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Error logging into account

**screenshot of downloaded items and extract folder:**

![image](https://user-images.githubusercontent.com/130945768/232360479-48800aa3-2d75-4f32-93c2-e0c9ee346cd8.png)

**Comment by DJSchaffner** [comment]
It seems like .NET is not installed. Did you just download it and put it there, or did you also install it? 
The runtime version should be enough by the way. SDK is not needed.

**Comment by DJSchaffner** [comment]
I think I know what the issue is. Thank you for reporting it, I will try to fix it later :)
It will require a new version of the tool though

**Comment by DJSchaffner** [comment]
Should be fixed now, please try again with the latest released version

**Comment by SolomonRed** [comment]
It is working now, thank you very much for making this!
